enum Mode {
  CHANGE_UNEMPLOYMENT,
  PROJECTIONS,
  WORKFORCE_SHARE
};

final int HEADER_HEIGHT = 38;
final int BLACK = #333333;
final int DARK_GRAY = #707070;
final int LIGHT_GRAY = #B0B0B0;

int REGULAR_SECTION_WIDTH = 220;

final int VISA_AMOUNT_ANCHOR_X = REGULAR_SECTION_WIDTH + 10;
final int VISA_AMOUNT_ANCHOR_Y = HEADER_HEIGHT + 15;

final int CONNECTION_WIDTH = 220;

int INCREASE_UNEMPLOYEMENT_ANCHOR_X;
int INCREASE_UNEMPLOYEMENT_ANCHOR_Y;

int UNEMPLOYEMENT_BEFORE_AFTER_ANCHOR_X;
int UNEMPLOYEMENT_BEFORE_AFTER_ANCHOR_Y;

int HYPOTHETICAL_UNEMPLOYMENT_ANCHOR_X;
int HYPOTHETICAL_UNEMPLOYMENT_ANCHOR_Y;

final int SUBTITLE_HEIGHT = 40;
final int RECORD_HEIGHT = 26;
final int START_RECORDS_Y = SUBTITLE_HEIGHT + RECORD_HEIGHT - 4;

final int VISA_AMOUNT_COLOR = #8da0cb;
final int NEW_UNEMPLOYMENT_COLOR = #fc8d62;
final int OLD_UNEMPLOYMENT_COLOR = #66c2a5;
final int HYPOTHETICAL_UNEMPLOYMENT_COLOR = #8da0cb;
final int VISA_AMOUNT_COLOR_TRANSPARENT = #508da0cb;
final int NEW_UNEMPLOYMENT_COLOR_TRANSPARENT = #50fc8d62;
final int OLD_UNEMPLOYMENT_COLOR_TRANSPARENT = #5066c2a5;
final int HYPOTHETICAL_UNEMPLOYMENT_COLOR_TRANSPARENT = #508da0cb;

PFont HEADER_FONT;
PFont REGULAR_FONT;
PFont SMALL_FONT;

void loadSemiconstants() {
  HEADER_FONT = loadFont("Lato-Regular-22.vlw");
  REGULAR_FONT = loadFont("Lato-Regular-14.vlw");
  SMALL_FONT = loadFont("Lato-Regular-11.vlw");

  boolean useSlopegraph = MODE == Mode.WORKFORCE_SHARE;
  if (useSlopegraph) {
    INCREASE_UNEMPLOYEMENT_ANCHOR_X = VISA_AMOUNT_ANCHOR_X + CONNECTION_WIDTH;
    INCREASE_UNEMPLOYEMENT_ANCHOR_Y = VISA_AMOUNT_ANCHOR_Y;
    REGULAR_SECTION_WIDTH = 220;
  } else {
    INCREASE_UNEMPLOYEMENT_ANCHOR_X = 16;
    INCREASE_UNEMPLOYEMENT_ANCHOR_Y = VISA_AMOUNT_ANCHOR_Y;
    REGULAR_SECTION_WIDTH = 300;
  }

  UNEMPLOYEMENT_BEFORE_AFTER_ANCHOR_X = INCREASE_UNEMPLOYEMENT_ANCHOR_X + REGULAR_SECTION_WIDTH + 32;
  UNEMPLOYEMENT_BEFORE_AFTER_ANCHOR_Y = VISA_AMOUNT_ANCHOR_Y;
  HYPOTHETICAL_UNEMPLOYMENT_ANCHOR_X = UNEMPLOYEMENT_BEFORE_AFTER_ANCHOR_X;
  HYPOTHETICAL_UNEMPLOYMENT_ANCHOR_Y = VISA_AMOUNT_ANCHOR_Y;
}
